name = "PlantClima"
uuid = "6929416b-c1e8-4b1c-a0ae-58fe036717ff"
authors = ["anaIFernst <ana.ferreiraernst@wur.nl> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
